server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: bullet

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/bullet/
  file:
    max-size: 1GB

